import argparse
import sys
import os
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import torch
import torch.nn as nn
import numpy as np
import random
import time
import copy

# Add parent directory to path to allow importing base_model, data_load, data_process, my_utiils
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

from utils import metrics_graph
from data_load import dataload
from data_process import process


from model import SOULCDR
from contrastive_loss import SupConLoss

FIXED_SEED = 0


def set_seed():
    """Set a fixed seed for reproducibility."""
    random.seed(FIXED_SEED)
    np.random.seed(FIXED_SEED)
    torch.manual_seed(FIXED_SEED)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(FIXED_SEED)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

def build_hetero_graph(nb_celllines, nb_drugs, device, cell_feature, drug_feature_dict, top_k=10):
    """
    Constructs the global heterogeneous graph edges and weights from PRE-LOADED data.
    """
    print("Constructing Global Heterogeneous Graph from Loaded Features...")
    
    # 1. Cell-Cell Similarity (PROGENy)
    # cell_feature is now expected to be the PROGENy dataframe or tensor
    if cell_feature is not None and len(cell_feature) > 0:
        # If it's a tensor/array, use it directly. If DataFrame, values.
        if torch.is_tensor(cell_feature):
             cell_feats = cell_feature.detach().cpu().numpy()
        elif hasattr(cell_feature, 'values'):
             cell_feats = cell_feature.values
        else:
             cell_feats = np.array(cell_feature)
             
        # Normalize? Cosine similarity handles magnitude, but scaling helps generic GNNs.
        # Here we just compute cosine sim.
        sim_mat_cell = cosine_similarity(cell_feats)
        np.fill_diagonal(sim_mat_cell, 0)
        
        top_k_indices = np.argsort(sim_mat_cell, axis=1)[:, -top_k:]
        
        src_list = []
        dst_list = []
        weight_list = []
        
        for r in range(nb_celllines):
            for c in top_k_indices[r]:
                src_list.append(r)
                dst_list.append(c)
                weight_list.append(sim_mat_cell[r, c])
                
        cell_edge_index = torch.tensor([src_list, dst_list], dtype=torch.long)
        cell_edge_weight = torch.tensor(weight_list, dtype=torch.float).unsqueeze(1)
    else:
        print("Warning: Cell feature (PROGENy) is empty. Using empty edges for Cell-Cell.")
        cell_edge_index = torch.empty((2, 0), dtype=torch.long)
        cell_edge_weight = torch.empty((0, 1), dtype=torch.float)

    # 2. Drug-Drug Similarity (Physicochemical)
    # drug_feature_dict is dict: drug_id -> {feat: val}
    # We need to extract them in ORDER corresponding to drug indices 0..nb_drugs-1
    # We assume the caller passes the ALIGNED tensor or we construct it here.
    # Actually, `process` already constructs `physicochemical_tensor` (N_drugs x NewDim).
    # Better to pass THAT tensor here.
    
    if drug_feature_dict is not None and len(drug_feature_dict) > 0:
        # Assuming drug_feature_dict is the tensor passed from process() output
        if torch.is_tensor(drug_feature_dict):
             drug_feats = drug_feature_dict.detach().cpu().numpy()
        elif isinstance(drug_feature_dict, dict):
             # Warning: Only robust if dict is already ordered 0..N-1, which it likely isn't if keys are PubChemIDs
             # But assuming user passed correct aligned data or raw dict
             drug_feats = np.array(list(drug_feature_dict.values()))
        elif hasattr(drug_feature_dict, 'values'):
             # Pandas DataFrame
             drug_feats = drug_feature_dict.values
        else:
             drug_feats = np.array(drug_feature_dict) 
             # Let's assume the caller passes the `physicochemical_tensor` generated by process().
             drug_feats = np.array(drug_feature_dict)
             
        sim_mat_drug = cosine_similarity(drug_feats)
        np.fill_diagonal(sim_mat_drug, 0)
        
        top_k_indices = np.argsort(sim_mat_drug, axis=1)[:, -top_k:]
        src_list = []
        dst_list = []
        weight_list = []
        
        for r in range(nb_drugs):
            for c in top_k_indices[r]:
                src_list.append(r)
                dst_list.append(c)
                weight_list.append(sim_mat_drug[r, c])
                
        drug_edge_index = torch.tensor([src_list, dst_list], dtype=torch.long)
        drug_edge_weight = torch.tensor(weight_list, dtype=torch.float).unsqueeze(1)
    else:
        print("Warning: Drug feature (Physicochemical) is empty. Using empty edges for Drug-Drug.")
        drug_edge_index = torch.empty((2, 0), dtype=torch.long)
        drug_edge_weight = torch.empty((0, 1), dtype=torch.float)
        
    # Construct Dictionaries (Global)
    edge_index_dict = {
        ('cell', 'similar_to', 'cell'): cell_edge_index.to(device),
        ('drug', 'similar_to', 'drug'): drug_edge_index.to(device)
    }
    edge_weight_dict = {
        ('cell', 'similar_to', 'cell'): cell_edge_weight.to(device),
        ('drug', 'similar_to', 'drug'): drug_edge_weight.to(device)
    }
    
    return edge_index_dict, edge_weight_dict

def get_batch_hetero_graph(global_edge_index_dict, global_edge_weight_dict, batch_drug_indices, nb_celllines, train_edge_subset=None, device='cpu'):
    """
    Slices the global heterogeneous graph to create a batch-specific subgraph.
    1. Cell-Cell: Keep ALL (since we use all cells per batch).
    2. Drug-Drug: Keep edges where Source AND Target are in `batch_drug_indices`.
       Re-index nodes from GlobalID -> BatchID (0..B-1).
    3. Responds: Construct from `train_edge_subset` (Local Batch Pairs).
    """
    
    batch_edge_index_dict = {}
    
    # 1. Cell-Cell (Keep All)
    batch_edge_index_dict[('cell', 'similar_to', 'cell')] = global_edge_index_dict[('cell', 'similar_to', 'cell')]
    # Weight handling if needed (HGTConv might not use weights in standard impl, but we can pass them)
    
    # 2. Drug-Drug (Filter & Re-map)
    d_idx_map = {global_id.item(): local_id for local_id, global_id in enumerate(batch_drug_indices)}
    
    global_dd_index = global_edge_index_dict[('drug', 'similar_to', 'drug')]
    
    # Find edges where both src and dst are in batch
    # This acts as an induced subgraph on the batch nodes
    mask_src = torch.isin(global_dd_index[0], batch_drug_indices)
    mask_dst = torch.isin(global_dd_index[1], batch_drug_indices)
    mask = mask_src & mask_dst
    
    subset_dd_index = global_dd_index[:, mask]
    
    # Remap indices to 0..BatchSize-1
    # We apply the map. Since size is small, a simple loop or vectorized lookup works.
    # Vectorized:
    # We can use bucketization or searchsorted if sorted, but here map is arbitrary.
    # Robust method:
    new_src = torch.tensor([d_idx_map[i.item()] for i in subset_dd_index[0]], device=device)
    new_dst = torch.tensor([d_idx_map[i.item()] for i in subset_dd_index[1]], device=device)
    
    batch_edge_index_dict[('drug', 'similar_to', 'drug')] = torch.stack([new_src, new_dst])
    
    # 3. Responds (Drug -> Cell) for structural connectivity in Message Passing
    # Uses known positive interactions in the training split for this batch
    if train_edge_subset is not None:
         # train_edge_subset: (N, 3) [Cell, Drug(Global), Label]
         # Filter positive edges only
         pos_mask = (train_edge_subset[:, 2] == 1)
         pos_edges = train_edge_subset[pos_mask]
         
         if len(pos_edges) > 0:
             # Cell IDs are 0..Nc (keep as is)
             # Drug IDs are Global. Map to Local.
             # Note: train_edge_subset should ideally ONLY contain drugs in this batch if passed correctly,
             # but we double check or remap.
             
             # The `train_edge_subset` passed from loop is `train_edge[mask]`.
             # Drug IDs in column 1 are Global Drug IDs (offset by 0? No, process subtracts offset).
             # Let's verify process(): `train[:, 1] -= nb_celllines`. So they are 0..Nd-1. Correct.
             
             # Map Global Drug ID -> Local Batch ID
             # subset_src_drug_global = pos_edges[:, 1]
             # To vectorized map:
             # It's possible some training edges point to drugs NOT in the batch?
             # No, we slice train_edge by `batch_drug_indices` in the loop.
             
             batch_d_ids = torch.tensor([d_idx_map[d.item()] for d in pos_edges[:, 1]], device=device)
             batch_c_ids = pos_edges[:, 0].clone().detach().to(device)
             
             batch_edge_index_dict[('drug', 'responds_to', 'cell')] = torch.stack([batch_d_ids, batch_c_ids])
         else:
             batch_edge_index_dict[('drug', 'responds_to', 'cell')] = torch.empty((2,0), dtype=torch.long, device=device)
    else:
         batch_edge_index_dict[('drug', 'responds_to', 'cell')] = torch.empty((2,0), dtype=torch.long, device=device)

    return batch_edge_index_dict

def run_proposed_experiment(args, similarity_feature, drug_feature, genomics_feature,
                            epigenomics_feature, transcriptomics_feature, proteomics_feature,
                            metabolomics_feature, pathway_feature, data_new, nb_celllines, 
                            nb_drugs, physicochemical_feature=None, verbose=True, k_folds=None, current_fold=0, 
                            permute_omics=False):
    """
    Run a single experiment for the Proposed Hybrid SOULCDR architecture
    
    Args:
        drug_feature: Dictionary {drug_id: [feat_mat, adj_list, degree_list]}
    """
    set_seed()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    if verbose:
        print(f"Using device: {device}")
        print("Running Stage-1 SOULCDR Model Experiment with Real Graph Batching")

    # Disable modalities based on flags
    if not args.use_genomics: genomics_feature = None
    if not args.use_epigenomics: epigenomics_feature = None
    if not args.use_transcriptomics: transcriptomics_feature = None
    if not args.use_proteomics: proteomics_feature = None
    if not args.use_metabolomics: metabolomics_feature = None
    if not args.use_pathway: pathway_feature = None
    # 0. Process Data (Build Graphs & Batches)
    # Returns aligned tensors, including decoupled similarity feature
    (drug_set, cellline_set, train_edge, label_pos, train_mask, val_mask, test_mask, 
     atom_shape, physicochemical_tensor, similarity_tensor) = process(
        drug_feature, genomics_feature, epigenomics_feature, transcriptomics_feature,
        proteomics_feature, metabolomics_feature, pathway_feature, similarity_feature,
        data_new, nb_celllines, nb_drugs, independent_test=True, test_ratio=0.1,
        data_split_seed=FIXED_SEED, physicochemical_feature=physicochemical_feature,
        k_folds=k_folds, current_fold=current_fold
    )
    
    # 0.1 Data Validation (Fail Loudly)
    if args.use_genomics and (genomics_feature is None or genomics_feature.shape[1] == 0):
        raise ValueError("Genomics enabled but feature data is missing or empty.")
    if args.use_epigenomics and (epigenomics_feature is None): # Epigenomics can be empty if not used, but if flag is True, it must exist. 
        # Note: epigenomics might be a list or different structure, check process() output.
        # process() returns tensor or None.
        if epigenomics_feature is None:
             raise ValueError("Epigenomics enabled but feature data is missing.")
    if args.use_transcriptomics and (transcriptomics_feature is None or transcriptomics_feature.shape[1] == 0):
        raise ValueError("Transcriptomics enabled but feature data is missing or empty.")
    if args.use_proteomics and (proteomics_feature is None or proteomics_feature.shape[1] == 0):
        raise ValueError("Proteomics enabled but feature data is missing or empty.")
    if args.use_metabolomics and (metabolomics_feature is None or metabolomics_feature.shape[1] == 0):
        raise ValueError("Metabolomics enabled but feature data is missing or empty.")
    if args.use_pathway and (pathway_feature is None or pathway_feature.shape[1] == 0):
        raise ValueError("Pathway enabled but feature data is missing or empty.")

    # 0.2 Data Alignment Verification
    # Verify that num_drugs in features matches num_drugs in graph
    # drug_feature is a dict {drug_id: [feat_mat, adj_list, degree_list]}
    if len(drug_feature) != nb_drugs:
         print(f"Warning: Drug feature count ({len(drug_feature)}) does not match nb_drugs ({nb_drugs}). This might act as a filter.")
         # raise ValueError(f"Drug feature count ({len(drug_feature)}) does not match nb_drugs ({nb_drugs})")
    
    # Verify cell line count in omics features matches nb_celllines
    # Note: process() might have filtered them, so we check the *processed* tensors
    # BUT process() returns `cellline_set` loader, not raw tensors easily.
    # However, `genomics_feature` here IS the processed tensor if we look at `process` return?
    # Wait, `process` returns `genomics_feature` as the *input* arg name? No, in python args are passed by assignment.
    # The `genomics_feature` variable in this scope is the *input* to process.
    # `process` returns `cellline_set`.
    # We should rely on `process` to have done its job, OR check the input tensors.
    # Input tensors should match `nb_celllines` (or the subset used).
    # Let's perform a basic check on the input if it's not None.
    if genomics_feature is not None and len(genomics_feature) != nb_celllines:
         print(f"Warning: Genomics samples ({len(genomics_feature)}) != nb_celllines ({nb_celllines}). This is okay if subsetting, but verify.")
    # We need the Pathway DataFrame (which was passed as pathway_feature but filtered in process)
    # process() returns tensors. `pathway_tensor`. 
    # But `build_hetero_graph` used cosine sim on the PROGENy dataframe from file.
    # To be consistent with "using passed data", we should use `pathway_tensor` returned by `process`.
    # `cellline_set` is a DataLoader wrapping the tensors. We can extract it.
    
    # Extract Cell Features
    # Cell loader has 1 batch usually (Full Batch of Cells).
    full_cell_batch = next(iter(cellline_set))
    # Unpack based on order: [0] genomics ... [5] pathway
    pathway_tensor_processed = full_cell_batch[5] # This is the Tensor used for Node Features if enabled
    
    # NEW: Use `similarity_tensor` returned by `process` (guaranteed alignment)
    if similarity_tensor is None:
         print("Warning: No distinct similarity feature provided. Using Pathway features for graph.")
         similarity_tensor = pathway_tensor_processed.to(device)
    else:
         similarity_tensor = similarity_tensor.to(device)

    global_edge_index, global_edge_weight = build_hetero_graph(
        nb_celllines, nb_drugs, device, 
        cell_feature=similarity_tensor,  # Use the explicit similarity tensor
        drug_feature_dict=physicochemical_tensor
    )

    genomics_dim = genomics_feature.shape[1] if genomics_feature is not None else 0
    epigenomics_in_channels = 1 if epigenomics_feature is not None else 0
    transcriptomics_dim = transcriptomics_feature.shape[1] if transcriptomics_feature is not None else 0
    proteomics_dim = proteomics_feature.shape[1] if proteomics_feature is not None else 0
    metabolomics_dim = metabolomics_feature.shape[1] if metabolomics_feature is not None else 0
    
    # Pathway dim comes from the feature shape (likely 11 distinct pathways in PROGENy)
    pathway_dim = pathway_feature.shape[1] if pathway_feature is not None else 0
    
    metadata = (
        ['drug', 'cell'],
        [
            ('drug', 'responds_to', 'cell'),
            ('cell', 'similar_to', 'cell'),
            ('drug', 'similar_to', 'drug')
        ]
    )

    model = SOULCDR(
        atom_shape=atom_shape,
        genomics_dim=genomics_dim,
        epigenomics_in_channels=epigenomics_in_channels,
        transcriptomics_dim=transcriptomics_dim,
        proteomics_dim=proteomics_dim,
        metabolomics_dim=metabolomics_dim,
        pathway_dim=pathway_dim,
        metadata=metadata,
        hidden_dim=args.hidden_channels,
        output_dim=args.output_channels,
        fusion_dim=args.fusion_dim,
        use_graph_transformer=args.use_graph_transformer,
        num_layers=2, 
        heads=4,
        graph_gnn_type=args.graph_GNN_type,
        drug_gnn_type=args.drug_gnn_type,
        global_gnn_type=args.global_gnn_type,
        active=args.active,
        use_transformer_drug=args.use_transformer_drug,
        variation=args.cell_line_module_variation
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    criterion = nn.BCEWithLogitsLoss()
    # Initialize Contrastive Loss (Stage-2)
    contrastive_criterion = SupConLoss(temperature=args.temperature)
    
    # Convert global masks/labels to Tensor on device
    train_mask = train_mask.to(device)
    val_mask = val_mask.to(device)
    test_mask = test_mask.to(device)
    label_pos = label_pos.to(device)
    if physicochemical_tensor is not None:
        physicochemical_tensor = physicochemical_tensor.to(device)

    # Convert train_edge to tensor for easier filtering
    train_edge_tensor = torch.tensor(train_edge, dtype=torch.long, device=device)

    def train(epoch):
        model.train()
        loss_temp = 0
        cls_temp = 0
        cont_temp = 0
        
        # Iterate over Batches of Drugs
        for batch, (drug, cell) in enumerate(zip(drug_set, cellline_set)):
            optimizer.zero_grad()
            
            drug.x = drug.x.to(device)
            drug.edge_index = drug.edge_index.to(device)
            drug.batch = drug.batch.to(device)
            
            # Drug Indices: Provided by updated `GraphDataset`
            # Shape: (BatchSize,)
            batch_drug_indices = drug.drug_idx.to(device)
            
            cell_data = [c.to(device) if c is not None else None for c in cell]
            
            # 1. Filter Train Edges for this Batch (for Responds Graph + Loss Calculation)
            # train_edge (N, 3). Col 1 is drug idx.
            # Keep rows where drug_idx is in batch_drug_indices
            mask_drug_in_batch = torch.isin(train_edge_tensor[:, 1], batch_drug_indices)
            batch_train_edges = train_edge_tensor[mask_drug_in_batch]
            
            # 2. Construct Real Batch Hetero Graph
            batch_edge_index_dict = get_batch_hetero_graph(
                global_edge_index, global_edge_weight, 
                batch_drug_indices, nb_celllines, 
                train_edge_subset=batch_train_edges, 
                device=device
            )
            
            # 3. Forward Pass
            # The model internally handles embedding generation for 
            # - Batch of Drugs (via drug.x, drug.batch) -> Size B
            # - All Cells -> Size Nc
            # HGT then runs on graph of size (B + Nc).
            # Pass physicochemical_tensor for the enhanced drug module (N_d, 64)
            out = model(
                drug_feature=drug.x, 
                drug_adj=drug.edge_index, 
                ibatch=drug.batch, 
                genomics_data=cell_data[0], 
                epigenomics_data=cell_data[1], 
                transcriptomics_data=cell_data[2],
                proteomics_data=cell_data[3], 
                metabolomics_data=cell_data[4], 
                pathway_data=cell_data[5],
                hetero_graph_edge_index_dict=batch_edge_index_dict,
                hetero_graph_edge_weight_dict=None, 
                physicochemical_features=physicochemical_tensor
            )
            
            z_d = out['drug_embeddings'] # (B, dim)
            z_c = out['cell_embeddings'] # (Nc, dim)
            
            # 4. Pairwise Predictions matches Valid Train Pairs
            # We have `batch_train_edges` [Cell, DrugGlobal, Label]
            # We need to act specifically on these pairs to compute loss efficiently?
            # OR we can do All-to-All and mask.
            # Given we have the `train_mask` global, we can use filtering.
            
            # Current Batch Size
            curr_bs = len(batch_drug_indices)
            
            # All-to-All approach (Robust for matrix operations)
            # z_pairs: (Nc * B)
            z_c_rep = z_c.repeat_interleave(curr_bs, dim=0) # C0...C0, C1...
            z_d_rep = z_d.repeat(nb_celllines, 1)           # D0...DB, D0...
            
            z_pair = torch.cat([z_d_rep, z_c_rep], dim=1)
            logits = model.predictor(z_pair).view(-1)
            
            # 5. Get Labels for these pairs
            # `label_pos` is (Nc * TotalDrugs).
            # We need columns corresponding to `batch_drug_indices`.
            # If `batch_drug_indices` are contiguous, we slice. If not, we gather.
            
            # Reshape global label and mask to (Nc, Nd)
            lbl_2d = label_pos.view(nb_celllines, nb_drugs)
            mask_2d = train_mask.view(nb_celllines, nb_drugs)
            
            # Gather columns
            batch_lbl = lbl_2d[:, batch_drug_indices].reshape(-1)
            batch_mask = mask_2d[:, batch_drug_indices].reshape(-1)

            # Compute Loss
            if batch_mask.sum() > 0:
                # Classification Loss
                loss_cls = criterion(logits[batch_mask], batch_lbl[batch_mask])
                
                # ADAPTIVE LOSS: Add Reconstruction Loss if using Autoencoder Variation
                if args.cell_line_module_variation == 'AE':
                    recon_loss = model.get_autoencoder_loss()
                    # Balance factor for reconstruction (lambda_ae = 0.1)
                    loss_cls = loss_cls + 0.1 * recon_loss
                
                # CONTRASTIVE LOSS (Stage-2) with Safety Policy
                loss_contrast = torch.tensor(0.0).to(device)

                if args.use_contrastive:
                    # Retrieve z_proj from current batch (calculated in forward pass if z_proj logic is active)
                    # We need to construct z_pair first if not returned directly for these specific indices (model logic does return logits for all pairs)
                    # But notice model.predictor was called manually on z_pair in line 382:
                    # z_pair = torch.cat([z_d_rep, z_c_rep], dim=1)
                    
                    # We need to compute z_proj for this z_pair
                    z_proj = model.projection_head(z_pair) # (Nc * B, dim)

                    # 1. Warm-up Phase Check
                    if epoch >= args.warmup_epochs:
                        # Filter for training mask
                        z_proj_train = z_proj[batch_mask]
                        labels_train = batch_lbl[batch_mask]
                        
                        # 2. Class Count Check
                        unique_labels = torch.unique(labels_train)
                        if len(unique_labels) >= 2:
                            # 3. Minimum Samples per Class Check (>= 2)
                            counts = torch.stack([(labels_train == c).sum() for c in unique_labels])
                            if torch.all(counts >= 2):
                                 # Sub-sampling to prevent OOM (Max 2048 pairs)
                                if z_proj_train.shape[0] > 2048:
                                    perm = torch.randperm(z_proj_train.shape[0])[:2048]
                                    z_proj_train = z_proj_train[perm]
                                    labels_train = labels_train[perm]
                                    
                                loss_contrast = contrastive_criterion(z_proj_train, labels_train)
                
                # Combine Losses
                loss = loss_cls + args.contrastive_weight * loss_contrast
                loss.backward()
                optimizer.step()
                loss_temp += loss.item()
                cls_temp += loss_cls.item()
                cont_temp += loss_contrast.item()
            
        if verbose: print(f'\nepoch: {epoch} | loss: {round(loss_temp, 4)}')
        return loss_temp, cls_temp, cont_temp

    def test(eval_mask):
        model.eval()
        loss_temp = 0
        all_preds = []
        all_lbls = []
        
        with torch.no_grad():
            for batch, (drug, cell) in enumerate(zip(drug_set, cellline_set)):
                drug.x = drug.x.to(device)
                drug.edge_index = drug.edge_index.to(device)
                drug.batch = drug.batch.to(device)
                batch_drug_indices = drug.drug_idx.to(device)
                
                cell_data = [c.to(device) if c is not None else None for c in cell]

                # Filter Edges for Graph Structure (Transductive)
                mask_drug = torch.isin(train_edge_tensor[:, 1], batch_drug_indices)
                batch_train_edges = train_edge_tensor[mask_drug]
                
                batch_edge_index_dict = get_batch_hetero_graph(
                    global_edge_index, global_edge_weight, 
                    batch_drug_indices, nb_celllines, 
                    train_edge_subset=batch_train_edges,
                    device=device
                )

                out = model(
                    drug_feature=drug.x,
                    drug_adj=drug.edge_index,
                    ibatch=drug.batch,
                    genomics_data=cell_data[0],
                    epigenomics_data=cell_data[1],
                    transcriptomics_data=cell_data[2],
                    proteomics_data=cell_data[3],
                    metabolomics_data=cell_data[4],
                    pathway_data=cell_data[5],
                    hetero_graph_edge_index_dict=batch_edge_index_dict
                )
                
                z_d = out['drug_embeddings']
                z_c = out['cell_embeddings']
                curr_bs = len(batch_drug_indices)
                z_c_rep = z_c.repeat_interleave(curr_bs, dim=0)
                z_d_rep = z_d.repeat(nb_celllines, 1)
                z_pair = torch.cat([z_d_rep, z_c_rep], dim=1)
                logits = model.predictor(z_pair).view(-1)
                
                lbl_2d = label_pos.view(nb_celllines, nb_drugs)
                mask_2d = eval_mask.view(nb_celllines, nb_drugs)
            
                batch_lbl = lbl_2d[:, batch_drug_indices].reshape(-1)
                batch_eval_mask = mask_2d[:, batch_drug_indices].reshape(-1)
                
                if batch_eval_mask.sum() > 0:
                     all_preds.append(torch.sigmoid(logits[batch_eval_mask]).cpu())
                     all_lbls.append(batch_lbl[batch_eval_mask].cpu())

            if len(all_preds) > 0:
                yp = torch.cat(all_preds).numpy()
                ytest = torch.cat(all_lbls).numpy()
                AUC, AUPR, F1, ACC = metrics_graph(ytest, yp)
            else:
                AUC, AUPR, F1, ACC = 0, 0, 0, 0
                
            if verbose:
                print(f'val auc: ' + str(round(AUC, 4)) + f'  val aupr: ' + str(round(AUPR, 4)))
        return AUC, AUPR, F1, ACC

    def test_final():
        model.eval()
        all_preds = []
        all_lbls = []
        
        with torch.no_grad():
            for batch, (drug, cell) in enumerate(zip(drug_set, cellline_set)):
                drug.x = drug.x.to(device)
                drug.edge_index = drug.edge_index.to(device)
                drug.batch = drug.batch.to(device)
                batch_drug_indices = drug.drug_idx.to(device)
                cell_data = [c.to(device) if c is not None else None for c in cell]

                # Use train edges for graph structure during testing (transductive)
                mask_drug = torch.isin(train_edge_tensor[:, 1], batch_drug_indices)
                batch_train_edges = train_edge_tensor[mask_drug]
                
                batch_edge_index_dict = get_batch_hetero_graph(
                    global_edge_index, global_edge_weight, 
                    batch_drug_indices, nb_celllines, 
                    train_edge_subset=batch_train_edges, 
                    device=device
                )

                out = model(
                    drug_feature=drug.x, 
                    drug_adj=drug.edge_index, 
                    ibatch=drug.batch, 
                    genomics_data=cell_data[0], 
                    epigenomics_data=cell_data[1], 
                    transcriptomics_data=cell_data[2],
                    proteomics_data=cell_data[3], 
                    metabolomics_data=cell_data[4], 
                    pathway_data=cell_data[5],
                    hetero_graph_edge_index_dict=batch_edge_index_dict,
                    hetero_graph_edge_weight_dict=None,
                    physicochemical_features=physicochemical_tensor
                )
                
                z_d = out['drug_embeddings']
                z_c = out['cell_embeddings']
                curr_bs = len(batch_drug_indices)
                z_c_rep = z_c.repeat_interleave(curr_bs, dim=0)
                z_d_rep = z_d.repeat(nb_celllines, 1)
                z_pair = torch.cat([z_d_rep, z_c_rep], dim=1)
                logits = model.predictor(z_pair).view(-1)
                
                lbl_2d = label_pos.view(nb_celllines, nb_drugs)
                mask_2d = test_mask.view(nb_celllines, nb_drugs)
            
                batch_lbl = lbl_2d[:, batch_drug_indices].reshape(-1)
                batch_test_mask = mask_2d[:, batch_drug_indices].reshape(-1)
                
                if batch_test_mask.sum() > 0:
                     all_preds.append(torch.sigmoid(logits[batch_test_mask]).cpu())
                     all_lbls.append(batch_lbl[batch_test_mask].cpu())

            if len(all_preds) > 0:
                yp = torch.cat(all_preds).numpy()
                ytest = torch.cat(all_lbls).numpy()
                AUC, AUPR, F1, ACC = metrics_graph(ytest, yp)
            else:
                AUC, AUPR, F1, ACC = 0, 0, 0, 0
                
            if verbose:
                print(f'\nFINAL TEST RESULTS:')
                print(f'test auc: ' + str(round(AUC, 4)) + f'  test aupr: ' + str(round(AUPR, 4)))
        return AUC, AUPR, F1, ACC

    best_val_auc = -1.0
    best_model_weights = None
    
    if args.save_training_curves:
        metrics_history = {'train_loss': [], 'cls_loss': [], 'cont_loss': [], 'val_auc': []}

    for epoch in range(args.epoch):
        if verbose: print('\nepoch: ' + str(epoch))
        train_loss, cls_loss, cont_loss = train(epoch)
        if verbose:
            print(f"Loss: {train_loss:.4f} (Cls: {cls_loss:.4f}, Cont: {cont_loss:.4f})")
        
        # VALIDATION Step
        val_AUC, val_AUPR, val_F1, val_ACC = test(val_mask)
        
        if val_AUC > best_val_auc: 
            best_val_auc = val_AUC
            best_model_weights = copy.deepcopy(model.state_dict())
            if verbose:
                print(f"--- Best model updated at epoch {epoch} (Val AUC: {best_val_auc:.4f}) ---")
    
    # Load best weights before final test 
    if best_model_weights is not None:
        model.load_state_dict(best_model_weights)
        if verbose:
            print(f"\n[Model Selection] Loaded best model weights (Validation AUC: {best_val_auc:.4f})")
    
    # Perform Final Evaluation on Test Set
    final_AUC, final_AUPR, final_F1, final_ACC = test_final()


    if args.save_training_curves:
        save_name_curves = f"curves_{args.graph_GNN_type}_{args.global_gnn_type}_GT{args.use_graph_transformer}_CL{args.contrastive_weight}_T{args.temperature}.npy"
        np.save(f"metrics_{save_name_curves}", metrics_history)
        if verbose: print(f"Saved training curves to metrics_{save_name_curves}")

    return final_AUC, final_AUPR, final_F1, final_ACC, epoch + 1




def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--epoch', type=int, default=200, help='number of epochs')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--hidden_channels', type=int, default=256)
    parser.add_argument('--output_channels', type=int, default=64)
    parser.add_argument('--fusion_dim', type=int, default=512, help='intermediate fusion dimension for cell line module')
    # Flags for proposed model
    parser.add_argument('--use_graph_transformer', action='store_true', default=True, help='Use Global Graph Transformer')
    
    # GNN Type Arguments
    parser.add_argument('--graph_GNN_type', type=str, default='heterogenous', choices=['homogenous', 'heterogenous'], help='Type of Graph GNN: homogenous or heterogenous')
    parser.add_argument('--drug_gnn_type', type=str, default='GIN', choices=['GCN', 'GAT', 'GIN', 'GraphSAGE'], help='GNN type for Drug Module')
    parser.add_argument('--global_gnn_type', type=str, default='SAGE', choices=['GCN', 'GAT', 'SAGE'], help='GNN type for Global Graph Processing')
    
    # Flags for modalities
    parser.add_argument('--use_genomics', action='store_true', default=False)
    parser.add_argument('--use_epigenomics', action='store_true', default=False)
    parser.add_argument('--use_transcriptomics', action='store_true', default=False)
    parser.add_argument('--use_proteomics', action='store_true', default=False)
    parser.add_argument('--use_metabolomics', action='store_true', default=False)
    parser.add_argument('--use_pathway', action='store_true', default=False)
    
    parser.add_argument('--genomics_file', type=str, default='genomics_mutation.csv', help='Filename for genomics data in final_dataset/')
    parser.add_argument('--k_fold', type=int, default=5, help='Number of folds for cross-validation')

    parser.add_argument('--contrastive_weight', type=float, default=0.001, help='Weight for SupCon loss (lambda)')
    parser.add_argument('--temperature', type=float, default=0.01, help='Temperature for contrastive loss')
    parser.add_argument('--warmup_epochs', type=int, default=10, help='Number of epochs to skip contrastive loss')
    parser.add_argument('--use_contrastive', action='store_true', default=False, help='Enable Contrastive Learning')
    
    # Stage-4 Experiments
    parser.add_argument('--permute_omics', action='store_true', default=False, help='Shuffle order of omics data at fusion stage')
    parser.add_argument('--cell_line_module_variation', type=str, default='original', choices=['original', 'AE', 'FC'], help='Variation of Cell Line Module')
    parser.add_argument('--use_transformer_drug', action='store_true', default=False, help='Use GPDRP-style Transformer Drug Module')
    parser.add_argument('--active', action='store_true', default=False, help='Enable Enhanced Drug Module with Physicochemical features')

    parser.add_argument('--save_predictions', action='store_true', default=False, help='Save y_true and y_pred to .npy files for ROC plotting')
    parser.add_argument('--save_training_curves', action='store_true', default=False, help='Save loss and AUC history to .npy for plotting training curves')
    parser.add_argument('--hyperparameter_tuning', action='store_true', default=False, help='Use independent validation split for tuning.')

    args = parser.parse_args()

    # VALIDATION: Disallow GCN with Heterogenous Graph
    # GCNConv requires square adjacency (spectral), not supported for bipartite (hetero) edges.
    if args.graph_GNN_type == 'heterogenous' and args.global_gnn_type == 'GCN':
        raise ValueError("Configuration Error: 'global_gnn_type=GCN' is technically incompatible with 'graph_GNN_type=heterogenous' for Drug-Cell bipartite edges (Spectral Convolution limitation). Please use 'SAGE' or 'GAT' for heterogeneous graphs.")


    # Log start time
    start_time = time.time()

    # Load data
    print("Loading data...")

    # Data Loading with Hardcoded Paths
    # Note: Using mutation/expression files as placeholders for missing omics (proteomics/metabolomics) 
    # since we disable them via flags anyway.
    # Root path for final_dataset
    final_dataset_root = '../../final_dataset'
    
    (drug_feature, genomics_feature, epigenomics_feature, transcriptomics_feature, 
     proteomics_feature, metabolomics_feature, pathway_feature, similarity_feature, 
     data_new, nb_celllines, nb_drugs, physicochemical_feature) = dataload(
        drug_feature_dir=os.path.join(final_dataset_root, 'drug_graph_feat'),
        response_file=os.path.join(final_dataset_root, 'response_pairs.csv'),
        genomics_csv=os.path.join(final_dataset_root, args.genomics_file),
        epigenomics_csv=os.path.join(final_dataset_root, 'epigenomics.csv'),
        transcriptomics_csv=os.path.join(final_dataset_root, 'transcriptomics.csv'),
        proteomics_csv=os.path.join(final_dataset_root, 'proteomics.csv'),
        metabolomics_csv=os.path.join(final_dataset_root, 'metabolomics.csv'),
        pathway_csv=os.path.join(final_dataset_root, 'pathway.csv'),
        similarity_csv=os.path.join(final_dataset_root, 'similarity.csv'),
        physiochemical_csv=os.path.join(final_dataset_root, 'physicochemical.csv'),
        use_genomics=args.use_genomics,
        use_epigenomics=args.use_epigenomics,
        use_transcriptomics=args.use_transcriptomics,
        use_proteomics=args.use_proteomics,
        use_metabolomics=args.use_metabolomics,
        use_pathway=args.use_pathway
    )
    
    final_AUC, final_AUPR, final_F1, final_ACC = 0, 0, 0, 0
    output_filename = "soulcdr_results.txt"

    # Run Experiment
    all_fold_metrics = []
    
    for fold in range(args.k_fold):
        if args.k_fold > 1:
            print(f"\n--- Running Fold {fold + 1}/{args.k_fold} ---")
        
        result = run_proposed_experiment(
            args,
            similarity_feature, # Pass similarity feature object
            drug_feature, genomics_feature, epigenomics_feature, transcriptomics_feature,
            proteomics_feature, metabolomics_feature, pathway_feature, data_new, nb_celllines, nb_drugs, physicochemical_feature, k_folds=args.k_fold, current_fold=fold,
            permute_omics=args.permute_omics
        )
        
        final_AUC, final_AUPR, final_F1, final_ACC, epochs_run = result
        all_fold_metrics.append([final_AUC, final_AUPR, final_F1, final_ACC, epochs_run])
        
        if args.k_fold > 1:
            print(f"Fold {fold + 1} Results -> AUC: {final_AUC:.4f}, AUPR: {final_AUPR:.4f}, F1: {final_F1:.4f}")

    # Calculate Aggregated Results
    all_fold_metrics = np.array(all_fold_metrics)
    avg_metrics = np.mean(all_fold_metrics, axis=0)
    std_metrics = np.std(all_fold_metrics, axis=0)

    final_AUC, final_AUPR, final_F1, final_ACC, avg_epochs = avg_metrics
    std_AUC, std_AUPR, std_F1, std_ACC, std_epochs = std_metrics
    
    # Use average metrics for logging
    epochs_run = avg_epochs # Log average epochs

    # Calculate elapsed time
    elapsed = time.time() - start_time
    
    # Log results
    print(f"\nExperiment Completed. Saving results to {output_filename}")
    
    if args.k_fold > 1:
        print(f'Average Total Epochs: {epochs_run:.2f}')
        print(f'Average Final_AUC: {final_AUC:.4f} +/- {std_AUC:.4f}')
        print(f'Average Final_AUPR: {final_AUPR:.4f} +/- {std_AUPR:.4f}')
        print(f'Average Final_F1: {final_F1:.4f} +/- {std_F1:.4f}')
        print(f'Average Final_ACC: {final_ACC:.4f} +/- {std_ACC:.4f}')
    else:
        print(f'Total Epochs: {epochs_run}')
        print(f'Final_AUC: {final_AUC:.4f}  Final_AUPR: {final_AUPR:.4f}  Final_F1: {final_F1:.4f}  Final_ACC: {final_ACC:.4f}')

    with open(output_filename, 'a') as f:
        f.write('---------------------------------------\n')
        f.write('Model: SOULCDR\n')
        f.write(f'Elapsed time: {round(elapsed, 4)}s\n')
        if args.k_fold > 1:
            f.write(f'K-Fold CV: {args.k_fold} folds\n')
        f.write(f'Fixed torch seed: {FIXED_SEED}\n')
        f.write(f'Drug GNN: {args.drug_gnn_type}\n')
        f.write(f'Graph Type: {args.graph_GNN_type}\n')
        f.write(f'Global GNN: {args.global_gnn_type}\n')
        f.write(f'Global Transformer: {args.use_graph_transformer}\n')
        if args.k_fold > 1:
            f.write(f'Average Total Epochs: {epochs_run:.2f}\n')
            f.write(f'Average Final_AUC: {final_AUC:.4f} +/- {std_AUC:.4f}\n')
            f.write(f'Average Final_AUPR: {final_AUPR:.4f} +/- {std_AUPR:.4f}\n')
            f.write(f'Average Final_F1: {final_F1:.4f} +/- {std_F1:.4f}\n')
            f.write(f'Average Final_ACC: {final_ACC:.4f} +/- {std_ACC:.4f}\n')
        else:
            f.write(f'Total Epochs: {epochs_run}\n')
            f.write(f'Final_AUC: {final_AUC:.4f}  Final_AUPR: {final_AUPR:.4f}  Final_F1: {final_F1:.4f}  Final_ACC: {final_ACC:.4f}\n')
        f.write('---------------------------------------\n')

# ==========================================
# Logging Implementation
# ==========================================
class Logger(object):
    def __init__(self, log_file):
        self.terminal = sys.stdout
        self.log = open(log_file, "a")

    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)
        self.log.flush()

    def flush(self):
        # Needed for python 3 compatibility
        self.terminal.flush()
        self.log.flush()

if __name__ == "__main__":
    # Initialize logging immediately
    import datetime
    
    # Create logs directory if it doesn't exist
    if not os.path.exists('logs'):
        os.makedirs('logs')
        
    # Generate log filename
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join('logs', f'drug_cell_experiment_{timestamp}.log')
    
    # Redirect stdout to Logger
    sys.stdout = Logger(log_file)
    
    print(f"Logging started: {log_file}")
    print(f"Command: {' '.join(sys.argv)}")
    print("==========================================")
    main()